/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sales.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.sales.util.Global;
import javax.swing.table.DefaultTableModel;
import org.sales.controller.ProductDAO;
import org.sales.controller.SalesDAO;
import org.sales.model.Product;
import org.sales.model.Sales;

/**
 *
 * @author Dell
 */
public class SellProduct extends javax.swing.JInternalFrame {
     DefaultTableModel model;
    /**
     * Creates new form SellProduct
     */
    public SellProduct() {
        initComponents();
        jLabel_CurrentDate.setText(new Date().toString());
        jLabel_User.setText(Global.user);
        model = new DefaultTableModel(null, new String[]{"ID", "Name", "Price", "Quantity", "Total"});
        jTable_Sales.setModel(model);
    }
    public void calculateTotal(){
        int rows = jTable_Sales.getRowCount();
        double gTotal = 0.0;
        for(int i = 0; i < rows; i++){
            double total = Double.parseDouble(jTable_Sales.getValueAt(i, 4).toString());
            gTotal += total;
        }
        jLabel_Total.setText(gTotal+"");
    }
    public void printBill(){
        int count = jTable_Sales.getRowCount();
        String str = "Namaste Super Market \nNewroad, Kathmandu\n";
        for(int i = 0;i<count; i++){
            str += jTable_Sales.getValueAt(i, 0).toString()+" ";
            str += jTable_Sales.getValueAt(i, 1).toString()+" ";
            str += jTable_Sales.getValueAt(i, 2).toString()+" ";
            str += jTable_Sales.getValueAt(i, 3).toString()+" ";
            str += jTable_Sales.getValueAt(i, 4).toString()+" ";
        }
        str += "\nGrand Total: "+jLabel_Total.getText();
        str += "\nThank you for visiting !!!";
        
        BillPrint ob = new BillPrint();
        ob.jTextArea_Bill.setLineWrap(true);
        ob.jTextArea_Bill.setText(str);
        try{
            ob.jTextArea_Bill.print();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel_CurrentDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jButton_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Sales = new javax.swing.JTable();
        jLabel_Total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_User = new javax.swing.JLabel();
        jButton_SavePrint = new javax.swing.JButton();

        jLabel_CurrentDate.setText("Current Date");

        jLabel1.setText("ID");

        jTextField_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdActionPerformed(evt);
            }
        });

        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jTable_Sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Sales);

        jLabel_Total.setText("Total");

        jLabel3.setText("Grand Total");

        jLabel2.setText("Logged in as: ");

        jLabel_User.setText("User");

        jButton_SavePrint.setText("Save & Print");
        jButton_SavePrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SavePrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_User)
                                .addGap(164, 164, 164)))
                        .addGap(31, 31, 31)
                        .addComponent(jButton_SavePrint))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_Total))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Delete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_CurrentDate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_CurrentDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Total)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_User)
                    .addComponent(jButton_SavePrint))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextField_Id.getText());
        ProductDAO pDAO = new ProductDAO();
        Product ob = pDAO.fetchData(id);
        if(ob.getId() > 0){
            model.addRow(new Object[]{ob.getId(), ob.getName(), ob.getPrice(), "1", ob.getPrice()});
            calculateTotal();
        }
        
    }//GEN-LAST:event_jTextField_IdActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        int row = jTable_Sales.getSelectedRow();
        model.removeRow(row);
        calculateTotal();
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jButton_SavePrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SavePrintActionPerformed
        // TODO add your handling code here:
        List <Sales> list = new ArrayList();
        int count = jTable_Sales.getRowCount();
        for(int i = 0; i<count; i++){
            Sales ob = new Sales();
            int pid = Integer.parseInt(jTable_Sales.getValueAt(i, 0).toString());
            int sid = Global.uid;
            int qty = Integer.parseInt(jTable_Sales.getValueAt(i, 3).toString());
            Date d = new Date();
            ob.setPid(pid);
            ob.setSid(sid);
            ob.setQty(qty);
            ob.setDate(d);
            list.add(ob);
        }
        SalesDAO sDAO = new SalesDAO();
        sDAO.saveData(list);
        printBill();
    }//GEN-LAST:event_jButton_SavePrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_SavePrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_CurrentDate;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JLabel jLabel_User;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_Sales;
    private javax.swing.JTextField jTextField_Id;
    // End of variables declaration//GEN-END:variables
}
